
image:
  repository: estafette/estafette-gke-preemptible-killer
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 50m
    memory: 128Mi

rbac:
  # If true, create & use RBAC resources
  create: false


blacklistHours: "09:00 - 12:00, 13:00 - 18:00"
whitelistHours: "02:00 - 06:00"

revisionHistoryLimit: 10

drainTimeout: 300
interval: 600

# you can specify existing secret with google serivce account used to interact with the Google Cloud API ...
# key name should be "google-service-account.json"
#existingSecret: "gke-preemptible-killer" 
# ... or put file content here:
googleServiceAccount: ""

livenessProbe:
  path: /metrics
  port: 9001
  initialDelaySeconds: 30
  timeoutSeconds: 1

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9001"

extraLabels: {}
  # team: tooling
